require("lazy").setup({
	require("plugins.indent"),
	require("plugins.tmux"),
	require("plugins.gitsigns"),
	require("plugins.lualine"),
	require("plugins.which-key"),
	require("plugins.telescope"),
	require("plugins.harpoon"),
	require("plugins.lspconfig"),
	require("plugins.conform"),
	require("plugins.ufo"),
	require("plugins.cmp"),
	require("plugins.todo-comments"),
	require("plugins.mini"),
	require("plugins.treesitter"),
	require("plugins.debug"),
	require("plugins.trouble"),
	require("plugins.indent-blankline"),
	require("plugins.lint"),
	require("plugins.autopairs"),
	require("plugins.autotag"),
	require("plugins.oil"),
	require("plugins.lazygit"),
	require("plugins.copilot"),
	require("plugins.code-companion"),
	require("plugins.theme"),
}, {
	ui = {
		icons = vim.g.have_nerd_font and {} or {
			cmd = "⌘",
			config = "🛠",
			event = "📅",
			ft = "📂",
			init = "⚙",
			keys = "🗝",
			plugin = "🔌",
			runtime = "💻",
			require = "🌙",
			source = "📄",
			start = "🚀",
			task = "📌",
			lazy = "💤 ",
		},
	},
})
