
# [shell]
# program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
opacity = 1
option_as_alt = "OnlyLeft"

[window.padding]
x = 10
y = 10

[font]
size = 14.0

[font.bold]
family = "SfMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.italic]
family = "SfMono Nerd Font"
style = "Italic"

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[env]

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/themes/dracula.toml"
]


